# **AG News Corpus**
### The AG News Corpus is a dataset for news categorization. It contains news articles from the AG's news website, categorized into four classes: World, Sports, Business, and Science/Technology.

**Data Preprocessing:**

In [ ]:
import pandas as pd

# Load the data into a DataFrame
file_path = 'train.csv'
df = pd.read_csv(file_path)
df

Class Index                                              Title  \
0               3                  Fears for T N pension after talks   
1               4  The Race is On: Second Private Team Sets Launc...   
2               4      Ky. Company Wins Grant to Study Peptides (AP)   
3               4      Prediction Unit Helps Forecast Wildfires (AP)   
4               4        Calif. Aims to Limit Farm-Related Smog (AP)   
...           ...                                                ...   
7595            1                                   Around the world   
7596            2                        Void is filled with Clement   
7597            2                             Martinez leaves bitter   
7598            3  5 of arthritis patients in Singapore take Bext...   
7599            3                             EBay gets into rentals   

                                            Description  
0     Unions representing workers at Turner   Newall...  
1     SPACE.com - TORONTO, Canada -- A second\team o...  
2     AP - A company founded by a chemistry research...  
3     AP - It's barely dawn when Mike Fitzpatrick st...  
4     AP - Southern California's smog-fighting agenc...  
...                                                 ...  
7595  Ukrainian presidential candidate Viktor Yushch...  
7596  With the supply of attractive pitching options...  
7597  Like Roger Clemens did almost exactly eight ye...  
7598  SINGAPORE : Doctors in the United States have ...  
7599  EBay plans to buy the apartment and home renta...  

[7600 rows x 3 columns]

In [ ]:

# 1-World, 2-Sports, 3-Business, 4-Sci/Tech
mapping = {1: "World", 2 : "Sports", 3: "Business", 4: "Sci/Tech"}
df["Class Description"] = df["Class Index"].map(mapping)
df


Class Index                                              Title  \
0               3                  Fears for T N pension after talks   
1               4  The Race is On: Second Private Team Sets Launc...   
2               4      Ky. Company Wins Grant to Study Peptides (AP)   
3               4      Prediction Unit Helps Forecast Wildfires (AP)   
4               4        Calif. Aims to Limit Farm-Related Smog (AP)   
...           ...                                                ...   
7595            1                                   Around the world   
7596            2                        Void is filled with Clement   
7597            2                             Martinez leaves bitter   
7598            3  5 of arthritis patients in Singapore take Bext...   
7599            3                             EBay gets into rentals   

                                            Description Class Description  
0     Unions representing workers at Turner   Newall...          Business  
1     SPACE.com - TORONTO, Canada -- A second\team o...          Sci/Tech  
2     AP - A company founded by a chemistry research...          Sci/Tech  
3     AP - It's barely dawn when Mike Fitzpatrick st...          Sci/Tech  
4     AP - Southern California's smog-fighting agenc...          Sci/Tech  
...                                                 ...               ...  
7595  Ukrainian presidential candidate Viktor Yushch...             World  
7596  With the supply of attractive pitching options...            Sports  
7597  Like Roger Clemens did almost exactly eight ye...            Sports  
7598  SINGAPORE : Doctors in the United States have ...          Business  
7599  EBay plans to buy the apartment and home renta...          Business  

[7600 rows x 4 columns]

 **Data Cleaning:**

In [ ]:
# lets check missing values
print("Missing values before cleaning:")
print(df.isnull().sum())
print(df.dropna(inplace=True))
print(df.isnull().sum())
df['Class Index'].isnull().sum()

Missing values before cleaning:
Class Index          0
Title                0
Description          0
Class Description    0
dtype: int64
None
Class Index          0
Title                0
Description          0
Class Description    0
dtype: int64


0

1. **Tokenization:** Converting paragraphs into sentences and words.
2. **StopWords:** Most common words.
3. **Stemming:** Converting the words to their base form.
4. **POS tag:** Part of speech of each word.
5. **Lemmatization:** gives the meaningful word in proper form.

Tokenization is the process breaking complex data like paragraphs into simple units called tokens. Tokens can be individual words, phrases or even whole sentences. In the process of tokenization, some characters like punctuation marks are discarded.

1. **Sentence tokenization** : split a paragraph into list of sentences using sent_tokenize() method
2. **Word tokenization** : split a sentence into list of words using word_tokenize() method

In [ ]:
!pip install nltk

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize

text = df["Description"].values[0]
words = word_tokenize(text)
print(words,"\ncount = ",len(words))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['Unions', 'representing', 'workers', 'at', 'Turner', 'Newall', 'say', 'they', 'are', "'disappointed", "'", 'after', 'talks', 'with', 'stricken', 'parent', 'firm', 'Federal', 'Mogul', '.'] 
count =  20


**Stop Words** refers to the most common words in a language (such as "the", "a", "an", "in") which helps in formation of sentence to make sense, but these words does not provide any significance in language processing so remove it .

In computing, stop words are words which are filtered out before or after processing of natural language data (text).

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
len(stop)
clean_words = [w for w in words if not w.lower() in stop]
print(clean_words,"\ncount = ",len(clean_words))
#freq of stopwords in description, which stop words are coming in title

['Unions', 'representing', 'workers', 'Turner', 'Newall', 'say', "'disappointed", "'", 'talks', 'stricken', 'parent', 'firm', 'Federal', 'Mogul', '.'] 
count =  15


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
#lets remove punctuation.
import string
punctuations = list(string.punctuation)
stop = stop + punctuations
clean_words = [w for w in words if not w.lower() in stop]
print(clean_words,"\ncount = ",len(clean_words))

['Unions', 'representing', 'workers', 'Turner', 'Newall', 'say', "'disappointed", 'talks', 'stricken', 'parent', 'firm', 'Federal', 'Mogul'] 
count =  13


**Stemming** is a normalization technique where list of tokenized words are converted into shorten root words to remove redundancy. Stemming is the process of reducing inflected (or sometimes derived) words to their word stem, base or root form.

In [ ]:
stem_words = ["play", "played", "playing"]
from nltk.stem import PorterStemmer
ps = PorterStemmer()
for w in stem_words:
    print (ps.stem(w))

play
play
play


**Lemmatization**

Major drawback of stemming is it produces Intermediate representation of word. Stemmer may or may not return meaningful word.

To overcome this problem , Lemmatization comes into picture. Stemming algorithm works by cutting suffix or prefix from the word.On the contrary Lemmatization consider morphological analysis of the words and returns meaningful word in proper form.

In [ ]:
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()
print(lem.lemmatize("painting", pos = 'n'))
print(lem.lemmatize("painting", pos = 'v'))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


painting
paint


In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.corpus import stopwords
import string
stops = stopwords.words('english') + list(string.punctuation)

In [ ]:
# Important functions to clean our data
from nltk.corpus import wordnet
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [ ]:
from nltk import pos_tag
def clean_review(words):
    words = word_tokenize(words)
    output_words = []
    for w in words:
        if w.lower() not in stops:
            pos = pos_tag([w])
            clean_word = lemmatizer.lemmatize(w, get_simple_pos(pos[0][1]))
            output_words.append(clean_word)
    return " ".join(output_words)

In [ ]:
print(df["Description"][6000])
clean_review(str(df["Description"][6000]))

US commercial crude oil inventories increased 800,000 barrels to 292.3 million in the week ending Nov. 12, the Energy Department reported Wednesday.


'US commercial crude oil inventory increase 800,000 barrel 292.3 million week end Nov. 12 Energy Department report Wednesday'

In [ ]:
df["clean_description"] = [clean_review(str(desc)) for ind, desc in df["Description"].items()]
df


Class Index                                              Title  \
0               3                  Fears for T N pension after talks   
1               4  The Race is On: Second Private Team Sets Launc...   
2               4      Ky. Company Wins Grant to Study Peptides (AP)   
3               4      Prediction Unit Helps Forecast Wildfires (AP)   
4               4        Calif. Aims to Limit Farm-Related Smog (AP)   
...           ...                                                ...   
7595            1                                   Around the world   
7596            2                        Void is filled with Clement   
7597            2                             Martinez leaves bitter   
7598            3  5 of arthritis patients in Singapore take Bext...   
7599            3                             EBay gets into rentals   

                                            Description Class Description  \
0     Unions representing workers at Turner   Newall...          Business   
1     SPACE.com - TORONTO, Canada -- A second\team o...          Sci/Tech   
2     AP - A company founded by a chemistry research...          Sci/Tech   
3     AP - It's barely dawn when Mike Fitzpatrick st...          Sci/Tech   
4     AP - Southern California's smog-fighting agenc...          Sci/Tech   
...                                                 ...               ...   
7595  Ukrainian presidential candidate Viktor Yushch...             World   
7596  With the supply of attractive pitching options...            Sports   
7597  Like Roger Clemens did almost exactly eight ye...            Sports   
7598  SINGAPORE : Doctors in the United States have ...          Business   
7599  EBay plans to buy the apartment and home renta...          Business   

                                      clean_description  
0     Unions represent worker Turner Newall say 'dis...  
1     SPACE.com TORONTO Canada -- second\team rocket...  
2     AP company found chemistry researcher Universi...  
3     AP 's barely dawn Mike Fitzpatrick start shift...  
4     AP Southern California 's smog-fighting agency...  
...                                                 ...  
7595  Ukrainian presidential candidate Viktor Yushch...  
7596  supply attractive pitch option dwindle daily -...  
7597  Like Roger Clemens almost exactly eight year e...  
7598  SINGAPORE Doctors United States warn painkille...  
7599  EBay plan buy apartment home rental service Re...  

[7600 rows x 5 columns]

In [ ]:
print(df["Description"][2], df["clean_description"][2], sep="\n")

AP - A company founded by a chemistry researcher at the University of Louisville won a grant to develop a method of producing better peptides, which are short chains of amino acids, the building blocks of proteins.
AP company found chemistry researcher University Louisville grant develop method produce well peptide short chain amino acid building block protein


**Count Vectorizer** is used to transform a given text into a vector on the basis of the frequency (count) of each word that occurs in the entire text.

It is used to convert a collection of text documents to a vector of term/token counts. It also enables the ​pre-processing of text data prior to generating the vector representation.

CountVectorizer creates a matrix in which each unique word is represented by a column of the matrix, and each text sample from the document is a row in the matrix. The value of each cell is nothing but the count of the word in that particular text sample.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
train_set = sorted({"the sky sky sky is blue", "the sun is bright", "how is you"})
count_vec = CountVectorizer(max_features = 3)
a = count_vec.fit_transform(train_set)
train_set, a.todense()

(['how is you', 'the sky sky sky is blue', 'the sun is bright'],
 matrix([[1, 0, 0],
         [1, 3, 1],
         [1, 0, 1]]))

In [ ]:
count_vec.get_feature_names_out()

array(['is', 'sky', 'the'], dtype=object)

## Accuracy with only title

In [ ]:
#lets clean the title
df["Title"] = [clean_review(desc) for ind, desc in df["Title"].items()]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

'''
train_test_split: Used for splitting the dataset into training and testing sets.
CountVectorizer: Converts a collection of text documents to a matrix of token counts.
MultinomialNB: Implements the Multinomial Naive Bayes algorithm for text classification.
accuracy_score: Measures the accuracy of the classifier.
'''

X_title = df['Title']
y = df['Class Index']

X_train, X_test, y_train, y_test = train_test_split(X_title, y, test_size=0.2, random_state=42)
X_train.head(), y_train.head()
# 1-World, 2-Sports, 3-Business, 4-Sci/Tech
len(df['Title']), len(df['Class Index'])
df['Class Index'].isnull().sum()

0

In [ ]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
y_train.isnull().sum()

0

In [ ]:
classifier = MultinomialNB()
classifier.fit(X_train_vec, y_train)

MultinomialNB()

In [ ]:
y_pred = classifier.predict(X_test_vec)
accuracy_title = accuracy_score(y_test, y_pred)
print("Accuracy with only title:", accuracy_title)

Accuracy with only title: 0.7868421052631579


## Accuracy with only description

In [ ]:
#lets clean the Description
df["Description"] = [clean_review(desc) for ind, desc in df["Description"].items()]

In [ ]:
X_desc = df['Description']

X_train, X_test, y_train, y_test = train_test_split(X_desc, y, test_size=0.2, random_state=42)

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

classifier = MultinomialNB()
classifier.fit(X_train_vec, y_train)

y_pred = classifier.predict(X_test_vec)
accuracy_desc = accuracy_score(y_test, y_pred)
print("Accuracy with only description:", accuracy_desc)


Accuracy with only description: 0.8769736842105263


## Accuracy with [title + description]

In [ ]:
X_title_desc = df['Title'] + ' ' + df['Description']

X_train, X_test, y_train, y_test = train_test_split(X_title_desc, y, test_size=0.2, random_state=42)

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

classifier = MultinomialNB()
classifier.fit(X_train_vec, y_train)

y_pred = classifier.predict(X_test_vec)
accuracy_title_desc = accuracy_score(y_test, y_pred)
print("Accuracy with [title + description]:", accuracy_title_desc)


Accuracy with [title + description]: 0.8848684210526315


## Stats for title and description:

In [ ]:
# Title
df['Title_len'] = df['Title'].apply(len)
title_stats = df['Title_len'].describe()

# Description
df['Desc_len'] = df['Description'].apply(len)
desc_stats = df['Desc_len'].describe()

print("Title Stats:\n", title_stats), print("\nDescription Stats:\n", desc_stats)

Title Stats:
 count    7600.000000
mean       36.016053
std        11.840087
min         4.000000
25%        28.000000
50%        35.000000
75%        42.000000
max        91.000000
Name: Title_len, dtype: float64

Description Stats:
 count    7600.000000
mean      142.754474
std        49.672850
min        30.000000
25%       113.000000
50%       138.000000
75%       163.000000
max       601.000000
Name: Desc_len, dtype: float64


(None, None)

## Accuracy with only title using RNN

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import numpy as np

X_title_desc = df['Title']
y = df['Class Index']

print(df.shape)
print(df)
print(df.columns.tolist())

X_train, X_test, y_train, y_test = train_test_split(X_title_desc, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)


(7600, 7)
      Class Index                                              Title  \
0               3                               Fears N pension talk   
1               4  Race Second Private Team Sets Launch Date Huma...   
2               4           Ky. Company Wins Grant Study Peptides AP   
3               4        Prediction Unit Helps Forecast Wildfires AP   
4               4              Calif Aims Limit Farm-Related Smog AP   
...           ...                                                ...   
7595            1                                       Around world   
7596            2                                  Void fill Clement   
7597            2                               Martinez leaf bitter   
7598            3  5 arthritis patient Singapore take Bextra Cele...   
7599            3                                    EBay get rental   

                                            Description Class Description  \
0     Unions represent worker Turner Newall say 

In [ ]:
# Convert labels to one-hot encoded format
label_encoder = LabelEncoder()
y_train_encoded = to_categorical(label_encoder.fit_transform(y_train))
y_test_encoded = to_categorical(label_encoder.transform(y_test))
num_classes = len(label_encoder.classes_)

print(y_train_encoded[0:4])
print(y_train[0:4])

# Vectorize the text data using CountVectorizer
vectorizer = CountVectorizer(max_features=100)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
print(X_train[0:2])
print(X_train_vec[0:2].todense())
print(X_train_vec.shape)


[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
4898    4
1616    1
6075    1
7333    3
Name: Class Index, dtype: int64
4898          Get Facts Microsoft Benchmarks
1616    Terror Suspect Escapes Bahrain Court
Name: Title, dtype: object
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
(6080, 100)


In [ ]:
# Reshape the input for SimpleRNN layer
timesteps = X_train_vec.shape[1]
input_dim = 1

X_train_vec_rnn = X_train_vec.toarray().reshape(-1, timesteps, input_dim)
X_test_vec_rnn = X_test_vec.toarray().reshape(-1, timesteps, input_dim)
print(X_train_vec_rnn.shape)
print(X_test_vec_rnn.shape)



(6080, 100, 1)
(1520, 100, 1)


In [ ]:
# Build the Sequential model with a SimpleRNN layer
model = Sequential()
model.add(SimpleRNN(32, input_shape=(timesteps, input_dim), activation='relu', use_bias=True))
model.add(Dense(32, activation='relu', use_bias=True))
model.add(Dense(32, activation='relu', use_bias=True))
model.add(Dense(4, activation='softmax'))

model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 32)                1056      
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 4)                 132       
                                                                 
Total params: 3332 (13.02 KB)
Trainable params: 3332 (13.02 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:

# Compile and train the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_vec_rnn, y_train_encoded, epochs=100, validation_data=(X_test_vec_rnn, y_test_encoded))

# Evaluate the model on the test set
y_pred_prob = model.predict(X_test_vec_rnn)
y_pred = np.argmax(y_pred_prob, axis=1)

# Calculate accuracy
accuracy_title_desc = accuracy_score(np.argmax(y_test_encoded, axis=1), y_pred)
print("Accuracy with [title:]", accuracy_title_desc)

Epoch 1/100
190/190 [==============================] - 5s 16ms/step - loss: 1.3772 - accuracy: 0.2594 - val_loss: 1.3636 - val_accuracy: 0.2882
Epoch 2/100
190/190 [==============================] - 3s 15ms/step - loss: 1.3599 - accuracy: 0.2862 - val_loss: 1.3562 - val_accuracy: 0.3066
Epoch 3/100
190/190 [==============================] - 5s 24ms/step - loss: 1.3537 - accuracy: 0.2918 - val_loss: 1.3514 - val_accuracy: 0.3079
Epoch 4/100
190/190 [==============================] - 3s 14ms/step - loss: 1.3496 - accuracy: 0.2893 - val_loss: 1.3472 - val_accuracy: 0.3184
Epoch 5/100
190/190 [==============================] - 3s 15ms/step - loss: 1.3475 - accuracy: 0.2880 - val_loss: 1.3450 - val_accuracy: 0.3178
Epoch 6/100
190/190 [==============================] - 3s 15ms/step - loss: 1.3449 - accuracy: 0.2934 - val_loss: 1.3423 - val_accuracy: 0.3158
Epoch 7/100
190/190 [==============================] - 4s 19ms/step - loss: 1.3436 - accuracy: 0.2980 - val_loss: 1.3470 - val_accuracy:

## Accuracy with only Description using RNN

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import numpy as np

X_title_desc = df['Description']
y = df['Class Index']

X_train, X_test, y_train, y_test = train_test_split(X_title_desc, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

# Convert labels to one-hot encoded format
label_encoder = LabelEncoder()
y_train_encoded = to_categorical(label_encoder.fit_transform(y_train))
y_test_encoded = to_categorical(label_encoder.transform(y_test))
num_classes = len(label_encoder.classes_)

print(y_train_encoded[0:4])
print(y_train[0:4])

# Vectorize the text data using CountVectorizer
vectorizer = CountVectorizer(max_features=300)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
print(X_train[0:2])
print(X_train_vec[0:2].todense())
print(X_train_vec.shape)

# Reshape the input for SimpleRNN layer
timesteps = X_train_vec.shape[1]  # Number of words in each document
input_dim = 1  # Each word is a feature

X_train_vec_rnn = X_train_vec.toarray().reshape(-1, timesteps, input_dim)
X_test_vec_rnn = X_test_vec.toarray().reshape(-1, timesteps, input_dim)
print(X_train_vec_rnn.shape)
print(X_test_vec_rnn.shape)

# Build the Sequential model with a SimpleRNN layer
model = Sequential()
model.add(SimpleRNN(32, input_shape=(timesteps, input_dim), activation='relu', use_bias=True))
model.add(Dense(32, activation='relu', use_bias=True))
model.add(Dense(32, activation='relu', use_bias=True))
model.add(Dense(4, activation='softmax'))

model.summary()
# Compile and train the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_vec_rnn, y_train_encoded, epochs=100, validation_data=(X_test_vec_rnn, y_test_encoded))

# Evaluate the model on the test set
y_pred_prob = model.predict(X_test_vec_rnn)
y_pred = np.argmax(y_pred_prob, axis=1)

# Calculate accuracy
accuracy_title_desc = accuracy_score(np.argmax(y_test_encoded, axis=1), y_pred)
print("Accuracy with [Description:]", accuracy_title_desc)

(6080,)
(1520,)
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
4898    4
1616    1
6075    1
7333    3
Name: Class Index, dtype: int64
4898    Steve Ballmer company give fact need compare W...
1616    terror suspect escape court Bahrain Monday jud...
Name: Description, dtype: object
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0

## Accuracy with [title + description] using RNN

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import numpy as np

X_title_desc = df['Title'] + ' ' + df['Description']
y = df['Class Index']

X_train, X_test, y_train, y_test = train_test_split(X_title_desc, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

# Convert labels to one-hot encoded format
label_encoder = LabelEncoder()
y_train_encoded = to_categorical(label_encoder.fit_transform(y_train))
y_test_encoded = to_categorical(label_encoder.transform(y_test))
num_classes = len(label_encoder.classes_)

print(y_train_encoded[0:4])
print(y_train[0:4])

# Vectorize the text data using CountVectorizer
vectorizer = CountVectorizer(max_features=300)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
print(X_train[0:2])
print(X_train_vec[0:2].todense())
print(X_train_vec.shape)

# Reshape the input for SimpleRNN layer
timesteps = X_train_vec.shape[1]  # Number of words in each document
input_dim = 1  # Each word is a feature

X_train_vec_rnn = X_train_vec.toarray().reshape(-1, timesteps, input_dim)
X_test_vec_rnn = X_test_vec.toarray().reshape(-1, timesteps, input_dim)
print(X_train_vec_rnn.shape)
print(X_test_vec_rnn.shape)

# Build the Sequential model with a SimpleRNN layer
model = Sequential()
model.add(SimpleRNN(32, input_shape=(timesteps, input_dim), activation='relu', use_bias=True))
model.add(Dense(32, activation='relu', use_bias=True))
model.add(Dense(32, activation='relu', use_bias=True))
model.add(Dense(4, activation='softmax'))

model.summary()
# Compile and train the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_vec_rnn, y_train_encoded, epochs=100, validation_data=(X_test_vec_rnn, y_test_encoded))

# Evaluate the model on the test set
y_pred_prob = model.predict(X_test_vec_rnn)
y_pred = np.argmax(y_pred_prob, axis=1)

# Calculate accuracy
accuracy_title_desc = accuracy_score(np.argmax(y_test_encoded, axis=1), y_pred)
print("Accuracy with [Title + Description:]", accuracy_title_desc)

(6080,)
(1520,)
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
4898    4
1616    1
6075    1
7333    3
Name: Class Index, dtype: int64
4898    Get Facts Microsoft Benchmarks Steve Ballmer c...
1616    Terror Suspect Escapes Bahrain Court terror su...
dtype: object
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 

## Accuracy with only title using LSTM

In [ ]:
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Tokenize text data
tokenizer = Tokenizer(num_words=1000)  # Limiting to 1000 most common words
tokenizer.fit_on_texts(df['Title'])
X = tokenizer.texts_to_sequences(df['Title'])

# Pad sequences to ensure uniform length
X = pad_sequences(X, maxlen=50)  # Assuming a max length of 50 for titles

# One-hot encode labels
y = pd.get_dummies(df['Class Index']).values

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the model
model = Sequential()
model.add(Embedding(1000, 32, input_length=50))
model.add(LSTM(32, activation='relu'))
model.add(Dense(4, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)

# Or you can use predictions to calculate accuracy
y_pred_prob = model.predict(X_test)
y_pred = [np.argmax(pred) for pred in y_pred_prob]
accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
print("Test Accuracy:", accuracy)


Epoch 1/50
171/171 [==============================] - 6s 20ms/step - loss: 1.3226 - accuracy: 0.4413 - val_loss: 1.2334 - val_accuracy: 0.6497
Epoch 2/50
171/171 [==============================] - 3s 19ms/step - loss: 0.9383 - accuracy: 0.6981 - val_loss: 0.8315 - val_accuracy: 0.6974
Epoch 3/50
171/171 [==============================] - 3s 19ms/step - loss: 0.6689 - accuracy: 0.7575 - val_loss: 0.7831 - val_accuracy: 0.7056
Epoch 4/50
171/171 [==============================] - 5s 28ms/step - loss: 0.5974 - accuracy: 0.7840 - val_loss: 0.8114 - val_accuracy: 0.7056
Epoch 5/50
171/171 [==============================] - 3s 19ms/step - loss: 0.6410 - accuracy: 0.7811 - val_loss: 0.8088 - val_accuracy: 0.7138
Epoch 6/50
171/171 [==============================] - 3s 19ms/step - loss: 0.5451 - accuracy: 0.7961 - val_loss: 0.8335 - val_accuracy: 0.7023
Epoch 7/50
171/171 [==============================] - 3s 17ms/step - loss: 0.5136 - accuracy: 0.8028 - val_loss: 0.8816 - val_accuracy: 0.6957

## Accuracy with only Description using LSTM

In [ ]:
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Tokenize text data
tokenizer = Tokenizer(num_words=1000)  # Limiting to 1000 most common words
tokenizer.fit_on_texts(df['Description'])
X = tokenizer.texts_to_sequences(df['Description'])

# Pad sequences to ensure uniform length
X = pad_sequences(X, maxlen=100)

# One-hot encode labels
y = pd.get_dummies(df['Class Index']).values

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the model
model = Sequential()
model.add(Embedding(1000, 32, input_length=100))
model.add(LSTM(32, activation='relu'))
model.add(Dense(4, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)

# Or you can use predictions to calculate accuracy
y_pred_prob = model.predict(X_test)
y_pred = [np.argmax(pred) for pred in y_pred_prob]
accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
print("Accuracy with [Description]:", accuracy)


Epoch 1/20
171/171 [==============================] - 7s 35ms/step - loss: 10.7639 - accuracy: 0.4984 - val_loss: 13.2320 - val_accuracy: 0.6974
Epoch 2/20
171/171 [==============================] - 7s 41ms/step - loss: 1.3685 - accuracy: 0.7010 - val_loss: 0.9899 - val_accuracy: 0.7138
Epoch 3/20
171/171 [==============================] - 6s 33ms/step - loss: 1.1444 - accuracy: 0.7416 - val_loss: 0.8709 - val_accuracy: 0.7303
Epoch 4/20
171/171 [==============================] - 7s 43ms/step - loss: 0.7967 - accuracy: 0.7588 - val_loss: 0.8368 - val_accuracy: 0.7632
Epoch 5/20
171/171 [==============================] - 6s 33ms/step - loss: 0.7225 - accuracy: 0.7822 - val_loss: 0.8751 - val_accuracy: 0.7977
Epoch 6/20
171/171 [==============================] - 8s 44ms/step - loss: 0.6726 - accuracy: 0.7948 - val_loss: 0.8955 - val_accuracy: 0.8010
Epoch 7/20
171/171 [==============================] - 6s 33ms/step - loss: 0.6283 - accuracy: 0.8037 - val_loss: 0.9311 - val_accuracy: 0.79

## Accuracy with [title + description] using LSTM

In [ ]:
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Tokenize text data
tokenizer = Tokenizer(num_words=1000)  # Limiting to 1000 most common words
X_title_desc = df['Title'] + ' ' + df['Description']
tokenizer.fit_on_texts(X_title_desc)
X = tokenizer.texts_to_sequences(X_title_desc)

# Pad sequences to ensure uniform length
X = pad_sequences(X, maxlen=100)

# One-hot encode labels
y = pd.get_dummies(df['Class Index']).values

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the model
model = Sequential()
model.add(Embedding(1000, 32, input_length=100))
model.add(LSTM(32, activation='relu'))
model.add(Dense(4, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)

# Or you can use predictions to calculate accuracy
y_pred_prob = model.predict(X_test)
y_pred = [np.argmax(pred) for pred in y_pred_prob]
accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
print("Accuracy with [Title + Description]:", accuracy)


Epoch 1/20
171/171 [==============================] - 10s 46ms/step - loss: 1.4434 - accuracy: 0.5236 - val_loss: 0.9806 - val_accuracy: 0.6530
Epoch 2/20
171/171 [==============================] - 7s 39ms/step - loss: 1.5218 - accuracy: 0.6683 - val_loss: 1.1830 - val_accuracy: 0.7138
Epoch 3/20
171/171 [==============================] - 7s 41ms/step - loss: 1.2965 - accuracy: 0.7253 - val_loss: 0.6818 - val_accuracy: 0.7615
Epoch 4/20
171/171 [==============================] - 8s 46ms/step - loss: 0.6923 - accuracy: 0.7719 - val_loss: 0.6550 - val_accuracy: 0.7714
Epoch 5/20
171/171 [==============================] - 6s 38ms/step - loss: 0.6171 - accuracy: 0.7785 - val_loss: 0.7429 - val_accuracy: 0.7747
Epoch 6/20
171/171 [==============================] - 8s 48ms/step - loss: 0.5765 - accuracy: 0.8041 - val_loss: 0.6161 - val_accuracy: 0.7895
Epoch 7/20
171/171 [==============================] - 6s 37ms/step - loss: 0.5667 - accuracy: 0.8200 - val_loss: 0.6292 - val_accuracy: 0.804